(() => {
  'use strict';
  const names=['Belize','Cayo','Corozal','Orange Walk','Stann Creek','Toledo'];
  let district=localStorage.getItem('swift.admin.district')||'',data=null,busy=false;
  const $=id=>document.getElementById(id);
  const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const options=(current,all=false)=>(all?'<option value="">All Belize</option>':'')+names.map(n=>'<option '+(n===current?'selected ':'')+'value="'+n+'">'+n+'</option>').join('');
  async function rpc(name,args={}){const {data,error}=await supabaseClient.rpc(name,args).abortSignal(AbortSignal.timeout(15000));if(error)throw error;return data;}
  function matches(row){if(!district)return true;const d=row.district||row.snapshot?.district||data?.workers?.find(w=>w.id===(row.worker_id||row.user_id||row.runner_id||row.driver_id||row.id))?.district;return d===district;}
  window.SwiftDistrictControl={matches,get district(){return district;},names};
  const panel=document.createElement('section');panel.id='nationwideControl';panel.hidden=true;panel.className='nationwide-control';panel.innerHTML='<div class="nationwide-heading"><div><h2>Belize control centre</h2><p>Districts, stores, workers, and order alerts.</p></div><label>Viewing<select id="adminDistrict"></select></label><button type="button" id="nationwideRefresh">Refresh</button></div><div id="districtOverview" class="district-overview"></div><p id="nationwideNotice" role="status"></p><details><summary>Stores and delivery coverage</summary><div id="districtStores"></div></details><details><summary>Store applications</summary><div id="districtStoreApplications"></div></details><details><summary>Worker districts</summary><p>Only you can transfer a worker. Active jobs must be finished first.</p><div id="districtWorkers"></div></details><p id="orderEmailHealth"></p>';
  $('dashboardScreen').prepend(panel);$('adminDistrict').innerHTML=options(district,true);
  const badge=document.createElement('p');badge.id='workerDistrictBadge';badge.hidden=true;badge.className='worker-district-badge';panel.after(badge);
  $('adminDistrict').onchange=()=>{district=$('adminDistrict').value;localStorage.setItem('swift.admin.district',district);draw();fetchOrders();refreshAdminRunnerTracker();window.refreshTeamRequests?.();window.dispatchEvent(new Event('swift-admin-district-changed'));};
  function draw(){if(!data)return;
    $('districtOverview').innerHTML=data.districts.filter(d=>!district||d.name===district).map(d=>'<article><strong>'+safe(d.name)+'</strong><span>'+d.orders+' orders · '+d.stores+' stores · '+d.workers+' workers</span><button type="button" data-toggle="'+safe(d.name)+'" data-enabled="'+String(!d.enabled)+'">'+(d.enabled?'Pause district':'Activate district')+'</button></article>').join('');
    $('districtStores').innerHTML=data.stores.filter(matches).map(s=>'<div class="nationwide-row"><strong>'+safe(s.category)+'</strong><span>'+safe(s.district)+' · '+(s.is_open==='yes'?'Open':'Closed')+'</span><button type="button" data-store="'+safe(s.category)+'">Edit coverage</button></div>').join('')||'<p>No stores in this district.</p>';
    $('districtStoreApplications').innerHTML=data.applications.filter(matches).map(a=>'<div class="nationwide-row"><div><strong>'+safe(a.store_name)+'</strong><p>'+safe(a.district)+' · '+safe(a.address)+' · '+safe(a.phone)+'</p></div><button type="button" data-review-store="'+a.id+'" data-approve="true">Approve</button><button type="button" data-review-store="'+a.id+'" data-approve="false">Reject</button></div>').join('')||'<p>No pending store applications.</p>';
    $('districtWorkers').innerHTML=data.workers.filter(matches).map(w=>'<div class="nationwide-row"><div><strong>'+safe(w.name)+'</strong><p>'+safe(w.kind)+' · '+safe(w.district)+' · '+(w.active?'Active':'Paused')+'</p></div><select aria-label="Transfer district for '+safe(w.name)+'" data-transfer-district="'+w.id+'">'+options(w.district)+'</select><button type="button" data-transfer="'+w.id+'">Transfer</button></div>').join('')||'<p>No workers in this district.</p>';
    $('orderEmailHealth').textContent='Your existing order alerts remain enabled.';
  }
  async function load(){if(currentProfile?.role!=='admin'||busy)return;busy=true;try{const firstLoad=!data;data=await rpc('swift_admin_nationwide');draw();if(firstLoad){fetchOrders();refreshAdminRunnerTracker();window.refreshTeamRequests?.();}$('nationwideNotice').textContent='Updated '+new Date().toLocaleTimeString()+'. New customer orders are accepted automatically.';}catch(e){$('nationwideNotice').textContent=e.message;}finally{busy=false;}}
  $('nationwideRefresh').onclick=load;
  panel.onclick=async e=>{const b=e.target.closest('button');if(!b)return;let action,args;
    if(b.dataset.toggle){action='swift_admin_district_enabled';args={p_district:b.dataset.toggle,p_enabled:b.dataset.enabled==='true'};}
    if(b.dataset.reviewStore){action='swift_admin_store_review';args={p_id:b.dataset.reviewStore,p_approve:b.dataset.approve==='true'};}
    if(b.dataset.transfer){action='swift_admin_transfer_district';args={p_user_id:b.dataset.transfer,p_district:panel.querySelector('[data-transfer-district="'+b.dataset.transfer+'"]').value};if(!confirm('Transfer this worker to '+args.p_district+'? This pauses their availability.'))return;}
    if(b.dataset.store){editStore(data.stores.find(s=>s.category===b.dataset.store));return;}
    if(!action)return;b.disabled=true;try{await rpc(action,args);await load();}catch(err){$('nationwideNotice').textContent=err.message;}finally{b.disabled=false;}
  };
  const dialog=document.createElement('dialog');dialog.id='districtStoreEditor';dialog.innerHTML='<form><h2>Store delivery coverage</h2><label>District<select name="district"></select></label><label>Store latitude<input name="lat" type="number" step="any" required></label><label>Store longitude<input name="lng" type="number" step="any" required></label><label>Delivery radius (km)<input name="radius" type="number" min="0.1" max="200" step="0.1"></label><label><input name="open" type="checkbox"> Accepting orders</label><p role="alert"></p><button type="button" data-close>Cancel</button><button type="submit">Save coverage</button></form>';document.body.append(dialog);let editing=null;
  function editStore(store){editing=store;const f=dialog.querySelector('form');f.elements.district.innerHTML=options(store.district);f.elements.lat.value=store.latitude??'';f.elements.lng.value=store.longitude??'';f.elements.radius.value=store.delivery_radius_km??'';f.elements.open.checked=store.is_open==='yes';f.querySelector('[role=alert]').textContent='';dialog.showModal();}
  dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type=submit]');b.disabled=true;try{await rpc('swift_admin_store_location',{p_category:editing.category,p_district:f.elements.district.value,p_lat:Number(f.elements.lat.value),p_lng:Number(f.elements.lng.value),p_radius:f.elements.radius.value?Number(f.elements.radius.value):null,p_open:f.elements.open.checked});dialog.close();await load();}catch(err){f.querySelector('[role=alert]').textContent=err.message;}finally{b.disabled=false;}};
  let identity=null;
  async function sync(){const id=currentUser?.id,role=currentProfile?.role;panel.hidden=role!=='admin';badge.hidden=!['runner','driver'].includes(role);if(id!==identity){identity=id;data=null;try{if(role==='admin')await load();else if(id){const status=await rpc('swift_worker_status');badge.textContent=(status.district||'District unavailable')+' team · Your registered district is fixed.';}}catch(e){badge.textContent=e.message;}}}
  setInterval(()=>{sync();if(!document.hidden&&currentProfile?.role==='admin')load();},15000);sync();
})();
