(() => {
 'use strict';
 const button=document.createElement('button');button.type='button';button.className='team-scan-launch';button.textContent='Scan customer QR';button.hidden=true;
 const paymentButton=document.createElement('button');paymentButton.type='button';paymentButton.className='team-scan-launch team-payment-launch';paymentButton.textContent='Scan payment QR';paymentButton.hidden=true;const hub=document.createElement('section');hub.id='workerScanPanel';hub.hidden=true;hub.className='team-payment-hub';hub.innerHTML='<div class="team-payment-heading"><span>SWIFTPAY & HANDOFF</span><h3>Collect payment. Confirm delivery.</h3><p>Choose the action that matches the customer’s request.</p></div><div class="team-payment-options"><article><h4>SwiftPay payment</h4><p>Enter the invoice amount, scan the customer’s payment QR, then confirm the handoff. Separate payments need confirmation on the customer’s phone.</p></article><article><h4>Cash delivery or ride</h4><p>Collect cash as usual. Scan the customer’s completion code to finish the delivery or trip.</p></article></div><ol class="team-payment-steps"><li><b>1</b>Start delivery or trip</li><li><b>2</b>Scan at arrival</li><li><b>3</b>Confirm payment & finish</li></ol>';document.querySelector('.workspace-content')?.append(hub);hub.querySelector('article').append(paymentButton);hub.querySelectorAll('article')[1].append(button);
 const dialog=document.createElement('dialog');dialog.className='team-scan-dialog';dialog.setAttribute('aria-labelledby','teamScanTitle');
 dialog.innerHTML='<header><div><p>SWIFTSHOP CONFIRMATION</p><h2 id="teamScanTitle">Scan the customer’s code</h2></div><button type="button" data-close aria-label="Close scanner">✕</button></header><p class="team-scan-intro">Confirm the right delivery or ride at handoff. Camera images stay on this device.</p><label class="team-payment-amount" data-payment-amount hidden>Amount charged (BZD)<input type="text" inputmode="decimal" placeholder="0.00" data-amount><small>BZ$0.15 is added separately. The customer confirms separate payments on their phone.</small></label><div class="team-scan-camera" hidden><video playsinline muted></video><span aria-hidden="true"></span></div><div class="team-scan-controls"><button type="button" data-camera>Open camera</button><label>Scan saved QR image<input type="file" accept="image/*" data-image></label></div><button type="button" data-retry hidden>Scan another code</button><p data-status role="status" aria-live="polite">Use your rear camera to scan the code on the customer’s screen.</p><section data-match hidden><h3></h3><p data-customer></p><p data-reference></p><button type="button" data-confirm>Confirm completion</button></section>';
 document.body.append(dialog);
 const $=selector=>dialog.querySelector(selector),video=$('video'),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
 let stream=null,version=0,timer=null,payload=null,processing=false,paymentMode=false,chargePoll=null,chargeRequest=null,chargeSession=null,enteredCents=null;
 function eligible(){return !!currentUser&&['runner','driver'].includes(currentProfile?.role);}
 function stop(){++version;clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;$('.team-scan-camera').hidden=true;}
 function reset(){stop();$('[data-retry]').hidden=true;dialog.dataset.scanState='idle';clearInterval(chargePoll);chargeSession=null;payload=null;$('[data-amount]').disabled=false;$('[data-match]').hidden=true;$('[data-confirm]').disabled=false;}
 async function call(name,args){const {data,error}=await supabaseClient.rpc(name,args).abortSignal(AbortSignal.timeout(12000));if(error)throw error;return data;}
 function amount(){const text=String($('[data-amount]').value||'').trim();if(!/^(?:0|[1-9]\d{0,5})(?:\.\d{1,2})?$/.test(text)||Math.round(Number(text)*100)<1||Math.round(Number(text)*100)>10000000)throw Error('Enter a valid BZD amount with up to two decimal places.');return Math.round(Number(text)*100);}
 function rpc(args){return paymentMode?call('swiftpay_scan_order_payment',{...args,p_amount_cents:enteredCents}):call('swift_scan_completion',args);}
 function identify(data){$('[data-match] h3').textContent=data.title;$('[data-customer]').textContent=data.name||'Customer';$('[data-reference]').textContent=(data.kind==='ride'?'Ride #':'Order #')+String(data.reference).slice(0,8).toUpperCase();$('[data-match]').hidden=false;}
 async function scanned(text){
  if(processing)return;stop();const token=version,uid=currentUser?.id;processing=true;dialog.dataset.scanState='loading';$('[data-retry]').hidden=false;$('[data-status]').textContent='QR detected. Checking payment and assignment…';
  try{if(!eligible())throw Error('Sign in as an approved runner or driver.');if(paymentMode){enteredCents=amount();if(text.startsWith('swiftshop-wallet:v1:')){const data=await call('swiftpay_counter_request',{p_payload:text,p_amount_cents:enteredCents,p_request_id:chargeRequest});if(!dialog.open||token!==version||uid!==currentUser?.id)return;dialog.dataset.scanState='waiting';chargeSession=data.id;$('[data-amount]').disabled=true;$('[data-match]').hidden=true;$('[data-status]').textContent='Request sent: BZ$'+(data.totalCents/100).toFixed(2)+' including fee. Waiting for the customer to confirm on their phone.';chargePoll=setInterval(async()=>{if(document.hidden||!chargeSession)return;try{const result=await call('swiftpay_counter_status',{p_id:data.id,p_request_id:chargeRequest});if(!dialog.open||chargeSession!==data.id||currentUser?.id!==uid)return;if(result.state==='paid'){clearInterval(chargePoll);dialog.dataset.scanState='paid';$('[data-status]').textContent='✓ Payment received · BZ$'+(result.totalCents/100).toFixed(2)+' including fee. Receipt #'+result.transactionId.slice(0,8).toUpperCase();document.dispatchEvent(new Event('swift-completion-confirmed'));}else if(result.expired||['declined','revoked'].includes(result.state)){clearInterval(chargePoll);$('[data-status]').textContent='Payment cancelled or expired. No charge was made.';}}catch(e){$('[data-status]').textContent=e.message;}},2500);return;}}const data=await rpc({p_payload:text,p_complete:false});if(!dialog.open||token!==version||uid!==currentUser?.id)return;dialog.dataset.scanState='ready';identify(data);$('[data-amount]').disabled=paymentMode;payload=text;$('[data-confirm]').disabled=!!data.completed;$('[data-confirm]').textContent=data.completed?'Already completed':data.swiftpay?'Confirm BZ$'+(data.totalCents/100).toFixed(2)+' payment & finish':data.kind==='ride'?'Confirm ride completed':'Confirm delivery handed over';$('[data-status]').textContent=data.completed?'This confirmation has already been recorded.':'Check the reference and customer. Confirm only after the handoff or trip is complete.';}
  catch(e){dialog.dataset.scanState='error';payload=null;$('[data-match]').hidden=true;$('[data-status]').textContent=e.message||'Could not check this code. Try again.';}
  finally{processing=false;}
 }
 function decode(source,width,height){const scale=Math.min(1,1280/Math.max(width,height));canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));ctx.drawImage(source,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);return window.jsQR(pixels.data,pixels.width,pixels.height,{inversionAttempts:'attemptBoth'})?.data;}
 async function camera(){
  if(processing)return;reset();const token=version;
  try{if(!eligible())throw Error('Sign in as a runner or driver.');if(paymentMode)amount();if(typeof window.jsQR!=='function')throw Error('Scanner could not load. Refresh this page and try again.');$('[data-status]').textContent='Opening camera…';if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera is unavailable. Use a saved QR image instead.');
   const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});
   if(token!==version||!dialog.open){next.getTracks().forEach(t=>t.stop());return;}stream=next;video.srcObject=stream;await video.play();$('.team-scan-camera').hidden=false;$('[data-status]').textContent='Camera ready. Hold the customer’s QR inside the frame; move closer if needed.';
   const frame=()=>{if(token!==version||!stream)return;try{if(video.readyState>=2){const text=decode(video,video.videoWidth,video.videoHeight);if(text){scanned(text);return;}}timer=setTimeout(frame,180);}catch{stop();$('[data-status]').textContent='Camera scan interrupted. Reopen camera or use a QR image.';}};frame();
  }catch(e){stop();$('[data-status]').textContent=e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in browser settings, or scan a saved QR image.':e.message||'Could not open camera.';}
 }
 function launch(payment){if(!eligible())return;paymentMode=payment;chargeRequest=crypto.randomUUID();enteredCents=null;reset();$('[data-payment-amount]').hidden=!payment;$('[data-amount]').value='';$('.team-scan-intro').textContent=payment?'Enter the amount before the BZ$0.15 fee. Scan only when the customer is ready to pay.':'Scan after handing over the delivery or finishing the ride.';$('#teamScanTitle').textContent=payment?'Scan payment QR':'Scan the customer’s code';$('[data-status]').textContent='Open your camera when the customer is ready.';dialog.showModal();}window.SwiftTeamScanner={payment(cents){launch(true);if(Number.isInteger(cents)&&cents>0)$('[data-amount]').value=(cents/100).toFixed(2);}};button.onclick=()=>launch(false);paymentButton.onclick=()=>launch(true);
 $('[data-retry]').onclick=()=>{chargeRequest=crypto.randomUUID();camera();};$('[data-camera]').onclick=camera;$('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('close',reset);
 dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
 $('[data-image]').onchange=async e=>{if(processing)return;reset();const file=e.target.files?.[0];e.target.value='';if(!file)return;const token=version;try{if(file.size>12*1024*1024)throw Error('Choose an image smaller than 12 MB.');const image=await createImageBitmap(file);let text;try{text=decode(image,image.width,image.height);}finally{image.close();}if(token!==version||!dialog.open)return;if(!text)throw Error('No readable QR code found. Try a clearer image.');await scanned(text);}catch(e){$('[data-status]').textContent=e.message;}};
 $('[data-confirm]').onclick=async()=>{if(!payload||processing)return;processing=true;dialog.dataset.scanState='loading';$('[data-status]').textContent='Confirming payment and completing the request…';$('[data-confirm]').disabled=true;try{const data=await rpc({p_payload:payload,p_complete:true});dialog.dataset.scanState='paid';identify(data);$('[data-status]').textContent=data.swiftpay?'SwiftPay payment received and request completed.':data.kind==='ride'?'Ride completion confirmed.':'Delivery handoff confirmed.';$('[data-confirm]').textContent='Completion recorded';if(typeof fetchOrders==='function')fetchOrders();document.dispatchEvent(new Event('swift-completion-confirmed'));}catch(e){dialog.dataset.scanState='error';$('[data-status]').textContent=e.message;$('[data-confirm]').disabled=false;}finally{processing=false;}};
 const init=window.initDashboard;window.initDashboard=function(){const result=init.apply(this,arguments);button.hidden=!eligible();paymentButton.hidden=!eligible();return result;};
 button.hidden=!eligible();paymentButton.hidden=!eligible();
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&stream)stop();});
 const logout=window.handleRunnerLogout;window.handleRunnerLogout=async function(){if(dialog.open)dialog.close();reset();button.hidden=true;paymentButton.hidden=true;return logout.apply(this,arguments);};
})();

