(()=>{
 const $=id=>document.getElementById(id), desk=$('dispatchEditor');if(!desk)return;
 const overview=document.createElement('section');overview.className='team-overview';overview.hidden=true;overview.setAttribute('aria-label','Order overview');
 for(const [key,label] of [['sent','New orders'],['preparing','Being prepared'],['ready','Ready for a runner'],['active','On the road']]){const b=document.createElement('button');b.type='button';if(key==='sent')b.className='team-incoming';const small=document.createElement('small');small.textContent=label;const count=document.createElement('b');count.id='teamCount'+key;count.textContent='—';b.append(small,count);b.onclick=()=>{if(key==='ready'){window.switchTab('available');return;}window.switchTab('dispatch');if(key==='active'){$('teamDispatchForm').open=true;$('adminLiveRuns')?.scrollIntoView({behavior:'smooth',block:'center'});}else{$('teamOrderStage').value=key==='ready'?'preparing':key;window.refreshTeamRequests?.();}};overview.append(b);}
 document.querySelector('.workspace-heading').after(overview);
 const workflow=document.createElement('div');workflow.className='team-workflow';workflow.innerHTML='<strong>Your order workflow</strong><span>1. Accept</span><i>→</i><span>2. Preparing</span><i>→</i><span>3. Send to runner</span>';desk.prepend(workflow);
 const tools=document.createElement('div');tools.className='team-order-tools';const search=document.createElement('input');search.id='teamOrderSearch';search.type='search';search.placeholder='Search customer, item or order';search.setAttribute('aria-label','Search customer orders');const stage=document.createElement('select');stage.id='teamOrderStage';stage.setAttribute('aria-label','Filter order stage');for(const [v,t] of [['all','All open orders'],['sent','New orders'],['accepted','Accepted'],['preparing','Accepted / preparing'],['dispatched','With a runner']]){const o=document.createElement('option');o.value=v;o.textContent=t;stage.append(o);}tools.append(search,stage);$('trackingRequestRows').before(tools);
 let delay;search.oninput=()=>{clearTimeout(delay);delay=setTimeout(()=>window.refreshTeamRequests?.(),200);};stage.onchange=()=>window.refreshTeamRequests?.();
 window.teamFilterRequests=rows=>{const q=search.value.trim().toLowerCase();return rows.filter(r=>(stage.value==='all'||(stage.value==='dispatched'?!!r.linked_order_id:stage.value==='preparing'?['accepted','preparing'].includes(r.phase)&&!r.linked_order_id:r.phase===stage.value))&&(!q||[r.id,r.snapshot?.customer_name,...(r.snapshot?.items||[]).map(i=>i.name)].some(v=>String(v||'').toLowerCase().includes(q))));};
 window.teamUpdateOverview=rows=>{overview.hidden=currentProfile?.role!=='admin';$('teamCountsent').textContent=rows.filter(r=>r.phase==='sent').length;$('teamCountpreparing').textContent=rows.filter(r=>['accepted','preparing'].includes(r.phase)&&!r.linked_order_id).length;$('teamCountready').textContent=allOrders.filter(isOpen).length;$('teamCountactive').textContent=allOrders.filter(o=>o.assigned_runner_id&&!['Delivered','Cancelled'].includes(o.status)).length;};
 const form=document.createElement('details');form.className='team-dispatch-form';form.id='teamDispatchForm';const summary=document.createElement('summary');summary.textContent='Create or review a runner dispatch';form.append(summary);
 for(const child of [...desk.children])if(child!==workflow&&child!==$('customerRequests'))form.append(child);desk.append(form);
 $('customerRequests').addEventListener('click',e=>{if(e.target.closest('button[data-action="dispatch"]'))form.open=true;},true);
 const oldInit=window.initDashboard;window.initDashboard=function(){const r=oldInit.apply(this,arguments);overview.hidden=currentProfile?.role!=='admin';workflow.hidden=currentProfile?.role!=='admin';return r;};
 const oldFetch=window.fetchOrders;let fetching=false;window.fetchOrders=async function(...args){if(fetching)return;fetching=true;try{return await oldFetch.apply(this,args);}finally{fetching=false;window.teamUpdateOverview?.(window.teamLatestRequests||[]);}};
})();